### ISSUE TITLE
Incorrect citation

### ISSUE THREAD

**Issue by UWN** [jariazavalverde/tau-prolog#1]
The [documentation page](http://tau-prolog.org/documentation) incorrectly reads:

> ... Prolog Standard by M. A. Covington.

The title of [this document](http://fsl.cs.illinois.edu/images/9/9c/PrologStandard.pdf) is, however:

> ISO Prolog: A Summary of the Draft Proposed Standard

So this is not the Prolog Standard. You can [obtain](https://stackoverflow.com/tags/iso-prolog/info) the Prolog Standard ISO/IEC 13211 from standardization bodies.

**Comment by UWN** [comment]
I will wait with further issues, until this is addressed

**Comment by jariazavalverde** [comment]
You're right, thanks for the observation. It is already corrected.
