### ISSUE TITLE
Missing Operator (+)/1 and Mute Top-Level

### ISSUE THREAD

**Issue by jburse** [jariazavalverde/tau-prolog#10]
It seems that (+)/1 is not defined, and subsequently when it
is used in the top-level in connection with numbers the usual
parsing error handling seems not to work anymore:

![tau_plus](https://user-images.githubusercontent.com/5411487/40625166-134bb926-62b1-11e8-92ba-8a3153c0dffc.png)

**Comment by jburse** [comment]
Here you see a shop, which tells me that there are now
probably two versions of the standard. But can't tell
you more right now, did not yet consult the new version.

The store is: https://global.ihs.com/ 

![standard_iso](https://user-images.githubusercontent.com/5411487/40625263-9eb6f1ce-62b1-11e8-98b7-27f7e47a2808.png)

**Comment by jburse** [comment]
One final remark: Please **don't panic**. I just wanted to document my
finding. Its of course your courtesy to priorize and to decide what
to do and when. Don't worry, be happy. Keep up the good work!

**Comment by jburse** [comment]
The plusoperator is here:
http://www.complang.tuwien.ac.at/ulrich/iso-prolog/dtc2#fdivplus

**Comment by jariazavalverde** [comment]
The `toString` method for syntax errors is already fixed. I'll reopen this issue to include the `+/1` operator.
