### ISSUE TITLE
Format of syntax errors

### ISSUE THREAD

**Issue by UWN** [jariazavalverde/tau-prolog#11]
Currently, the format of syntax errors does not conform to ISO.

Now: `error(syntax_error(line(1), column(21), found('.'), cause(', or ] expected')))`

Instead, the format should be as follows:

ISO: `error(syntax_error(', or ] expected'), Imp_def)`

Note that the argument of `syntax_error/1` must be an atom. You cannot put more information into it.

Above, Imp_def is an argument you can defined as you like.  Maybe:

`Imp_def = [line(1), column(21), found('.')]`

**Comment by jariazavalverde** [comment]
![format of syntax errors](https://user-images.githubusercontent.com/5055295/40651419-f207e5f2-6335-11e8-8ed7-3d114936ba95.png)
