### ISSUE TITLE
Cut (!) in DCG grammar rule

### ISSUE THREAD

**Issue by rslemos** [jariazavalverde/tau-prolog#19]
The following program works in SWI-Prolog (I don't know if it is ISO though):

```
a --> b, !, b.
b --> "b".
```
```
?- a(X, []), atom_codes(L, X).
X = [98, 98],
L = bb.
?-
```

In tau-prolog it throws the error: `uncaught exception: error(existence_error(procedure, '!/2'), 'a/2')`.

The `!` should not be augmented with differential lists.

**Comment by UWN** [comment]
Your example is fine with respect to the current ISO draft with `set_prolog_flag(double_quotes, codes)`.
