### ISSUE TITLE
The character sequence { } should be viewed an atom.

### ISSUE THREAD

**Issue by jburse** [jariazavalverde/tau-prolog#20]
In the iso standard we find two strange atoms in section 6.3.1.3. Namely [] and {}. Since they are atoms the can be also used as functors. GNU Prolog can do this, see the first query:

![gnu_cando](https://user-images.githubusercontent.com/5411487/41342542-c7de4b90-6efc-11e8-8795-7a2c51ce6954.png)

**Comment by jburse** [comment]
If I try tau Prolog I get the following unexpected result for the first query:

![set_notation](https://user-images.githubusercontent.com/5411487/41342589-e6d89820-6efc-11e8-816e-b5bac7f575fd.png)

**Comment by UWN** [comment]
Also `{ /**/ }` is *one atom*!

**Comment by jburse** [comment]
Yes, what Ulrich Neumerkel says, is a consequence of 
6.3.1.3 and if you dig deeper, and then find:
```
6.4 Tokens
close curly = [ layout text sequence ] close curly token
```

**Comment by jariazavalverde** [comment]
Fixed, thanks! `{1,2}` is still shown as `{}((1,2))`, but I have in mind to change it (with #14).

![[] and {} atoms](https://user-images.githubusercontent.com/5055295/41349288-bf71476a-6f0f-11e8-8c35-c8072f2b539f.png)

**Comment by jburse** [comment]
You would need some special casing in your code, when handling 
quoted(true), to avoid writing '{}'. After all {} is a legal unquoted atom, 
so it doesn't need some quotes. 

You can also check GNU Prolog in this matter:

![grafik](https://user-images.githubusercontent.com/5411487/41368846-6f1ac794-6f43-11e8-85e4-cef8865463a0.png)
