### ISSUE TITLE
Syntax: Not enough lookahead

### ISSUE THREAD

**Issue by UWN** [jariazavalverde/tau-prolog#23]
```p(0'\
\
+'1).```

Should be equivalent to `p(0+1).`, but is currently a syntax error.

http://tau-prolog.org/sandbox/VUo27QUZ
http://www.complang.tuwien.ac.at/ulrich/iso-prolog/conformity_testing#213

**Comment by UWN** [comment]
How can I see the update? Maybe show in the sandbox the version number & update time

**Comment by jariazavalverde** [comment]
When we leave the beta version, we'll add a flag to control the version. Meanwhile, I've added in the sandbox the date of modification of the files in the server. You could take that number as version.

![update](https://user-images.githubusercontent.com/5055295/41590678-df23ce82-73b7-11e8-8bea-9447882b1c96.png)
