### ISSUE TITLE
length(X,X) hangs

### ISSUE THREAD

**Issue by jburse** [jariazavalverde/tau-prolog#28]
I have the same problem in my system, but will do a simple succ/2 
based fix in the next release. Your system hangs:

![grafik](https://user-images.githubusercontent.com/5411487/42392330-bbd82150-8152-11e8-864e-bf9bd6db0423.png)

![grafik](https://user-images.githubusercontent.com/5411487/42392319-b10bde92-8152-11e8-9c0d-aed5e1cf15e8.png)

**Comment by jburse** [comment]
See also discussion here, which has some musing, why an
herr here would be not the worst idea, and can also be derived
from a bootstrapped spec:

https://groups.google.com/d/msg/comp.lang.prolog/wrfhTDyT6zw/qRFTY_F3AQAJ

**Comment by jariazavalverde** [comment]
Interesting. Thanks for the report.

**Comment by jariazavalverde** [comment]
Note that, according to [**this**](http://www.complang.tuwien.ac.at/ulrich/iso-prolog/length), the loop is ok.

**Comment by jburse** [comment]
Very difficult what these tests should mean. 
I see for example in the Ulrich Neumerkel tests:

`length(L,-1). | domain_error(not_less_than_zero,-1)`

But then in an old draft:
```
length(List, -2).
   Fails
```
https://www.complang.tuwien.ac.at/ulrich/iso-prolog/N208

**Comment by jburse** [comment]
Maybe put this enhancement on "hold". Not sure.

I am currently experimenting with using succ/2. 
And then I get the following results:

![grafik](https://user-images.githubusercontent.com/5411487/42404352-80f64090-8188-11e8-8d23-1ca07f75e3ca.png)

**Comment by jariazavalverde** [comment]
I think is more efficient check directly if the two arguments are the same (non anonymous) variable, instead of using the `succ/2` predicate.

```javascript
// length/2
"length/2": function( thread, point, atom ) {
	var list = atom.args[0], length = atom.args[1];
	if( !pl.type.is_variable( length ) && !pl.type.is_integer( length ) ) {
		thread.throwError( pl.error.type( "integer", length, atom.indicator ) );
	} else if( pl.type.is_integer( length ) && length.value < 0 ) {
		thread.throwError( pl.error.domain( "not_less_than_zero", length, atom.indicator ) );
	} else {
		// CHECK length(X,X) or length([...|X],X)
		var pointer = list;
		while( pl.type.is_term( pointer ) && pointer.indicator === "./2" )
			pointer = pointer.args[1];
                //  SAME VARIABLE, ERROR
		if( pl.type.is_variable( pointer ) && pl.type.is_variable( length ) && pointer.id === length.id && length.id !== "_" ) {
			thread.throwError( pl.error.type( "integer", new pl.type.Term( "[]", [] ), atom.indicator ) );
                // RUN LENGTH
		} else {
			var newgoal = new pl.type.Term("length", [list, new pl.type.Num(0, false), length]);
			if( pl.type.is_integer( length ) )
				newgoal = new pl.type.Term( ",", [newgoal, new pl.type.Term( "!", [] )] );
			thread.prepend( [new pl.type.State(point.goal.replace(newgoal), point.substitution, point)] );
		}
	}
},

// length/3
// DO NOT EXPORT
"length/3": [
	new pl.type.Rule(new pl.type.Term("length", [new pl.type.Term("[]", []),new pl.type.Var("N"),new pl.type.Var("N")]), null),
	new pl.type.Rule(new pl.type.Term("length", [new pl.type.Term(".", [new pl.type.Var("_"),new pl.type.Var("X")]),new pl.type.Var("A"),new pl.type.Var("N")]), new pl.type.Term(",", [new pl.type.Term("is", [new pl.type.Var("B"),new pl.type.Term("+", [new pl.type.Var("A"),new pl.type.Num(1, false)])]),new pl.type.Term("length", [new pl.type.Var("X"),new pl.type.Var("B"),new pl.type.Var("N")])]))
],
```

**Comment by jburse** [comment]
Yes, I see, after the while. Such things 
can be more easily done natively. 

Possibly doing it in Prolog code would already need 
a nonvar check to only do the matching [_|_] in 

the while loop.

**Comment by jburse** [comment]
Thats the monotonicity argument. Doesn't work for succ itself:

```
?- succ(2,-1).
ERROR: Domain error: `not_less_than_zero' expected, found `-1'

?- succ(2,X), X== -1.
false.
```

**Comment by UWN** [comment]
@jburse: I am not sure that @jariazavalverde is interested in your considerations.

In any case, the property of monotonicity is always taken modulo errors, non-termination, and resource consumption.

The examples you give are by no means specific to the prologue. In fact:

```
| ?- char_code(a,-1).
! Representation error in argument 2 of char_code/2
! invalid character code
! goal:  char_code(a,-1)
| ?- char_code(a,X), X = -1.
no
```

**Comment by jburse** [comment]
@UWN What Prolog system did you test? I don't get this error:

![char_code](https://user-images.githubusercontent.com/5411487/42416180-db2b4b02-8267-11e8-8f9c-cb724b25928a.png)

I don't think the error you showed makes any sense. Since
the second argument is output, if the first argument is bound.
You can think in modes. If the mode is (+,-) no need to

check the type of the - argument position. Also I have
never heard something like modulo errors, non-termination.
monotonicity should also hold modulo errors, non-termination.

Hope this helps.

**Comment by jburse** [comment]
Tau Prolog produces the same result. In my opinion the
result is sufficient, no need for some error message terror:

![tau_char](https://user-images.githubusercontent.com/5411487/42416197-48318806-8268-11e8-9171-082ad4857569.png)

**Comment by jburse** [comment]
After an observation by Ulrich Neumerkel I have rolled back my change,
but for some system there might be still an issue. Sorry for disturbing.

>     I have rolled back my changes to length/2. I think
>     your observation in the Tau Prolog issue, that both:
> 
>     ?- length(X, L), X = L.
> 
>     And:
> 
>     ?- length(X, X).
> 
>     Can loop, tells me aswell that looping is ok. But
>     since the predicate is tail recursive, it will not
>     consume a lot of stack, and loop quite long,
> 
>     but its still interuptible, since it is written
>     in Prolog, so it responds to thread signal. For
>     a more low level implementation, the
> 
>     loop might be a vulnerability, since it might
>     possibly crash the system. So a SWISH length(X,X)
>     might really be a problem for the system. Not sure.

**Comment by UWN** [comment]
@jariazavalverde: Please note that Jekejeke is not conforming to the ISO standard.

**Comment by jburse** [comment]
@jariazavalverde: Please note that Jekejeke is conforming to the ISO standard.
