### ISSUE TITLE
nth0/3 can be bidirectional

### ISSUE THREAD

**Issue by jburse** [jariazavalverde/tau-prolog#29]
Currently nth0/3 is not yet bidirectional. Frankly, this is 
a pitty, since I know a few applications where nth0/3 is
also used with another mode.

![grafik](https://user-images.githubusercontent.com/5411487/42404856-85cb1618-818d-11e8-845a-ff632cfc44c6.png)

**Comment by jburse** [comment]
Here is the test result for SWI-Prolog:

![grafik](https://user-images.githubusercontent.com/5411487/42404901-136076c6-818e-11e8-990a-dc1ad980746e.png)

**Comment by jariazavalverde** [comment]
Done!
