### ISSUE TITLE
Too many parenthesis in term writing

### ISSUE THREAD

**Issue by jburse** [jariazavalverde/tau-prolog#35]
Just by accident I stepped over this little glitch:

![grafik](https://user-images.githubusercontent.com/5411487/42629128-a97913be-85d2-11e8-9d60-75b71300b6b0.png)

**Comment by jburse** [comment]
You can compare with GNU Prolog or any other Prolog system:

![grafik](https://user-images.githubusercontent.com/5411487/42629163-c4abde50-85d2-11e8-9681-41f17c95e0a0.png)

**Comment by UWN** [comment]
@jariazavalverde: Please note that this should rather have the tag "iso conforming". See [7.10.5](http://www.complang.tuwien.ac.at/ulrich/iso-prolog/draft-7.10.5#h)
