### ISSUE TITLE
It could be the case that not all errors in the program are reported

### ISSUE THREAD

**Issue by jburse** [jariazavalverde/tau-prolog#36]
I was playing around with the Tau Prolog sandbox. My expectation
was to gain some information whether an export/1 directive
exists or not. If it exists I wouldn't see an error, and if it doesn't
exists I would get some error. Neither happens right now:

![grafik](https://user-images.githubusercontent.com/5411487/42688834-3863391c-869e-11e8-9dd8-971fd15849ab.png)

**Comment by jariazavalverde** [comment]
When Tau Prolog doesn't show any output it's because there is a JavaScript error. You can see it in the browser console (for future issues).

We don't have implemented the `export/1` directive yet.

**Comment by UWN** [comment]
@jariazavalverde: Please have a look at the way how [SICStus](https://sicstus.sics.se/sicstus/docs/latest4/html/sicstus.html/ref_002dmod.html#ref_002dmod) offers module. ((The module standard itself permits a lot of incarnations. SICStus would be one, too))

**Comment by ghost** [comment]
@UWN  Sorry, but the error has nothing to do with module system, 
and SICstus will not be of any help here. Already modules are not mentioned in the 
title of the error "It could be the case that not all errors in the program are reported". 

The error is in what the toplevel shows when the program is not accepted:

![where_is_the_error](https://user-images.githubusercontent.com/5411487/42709902-5e577e14-86e2-11e8-80eb-0b62d79c585b.gif)

**Comment by ghost** [comment]
The problem is that not all browsers have an error console. For example I don't find one in the Safari Browser so easily. I just checked on a MacBook. You need to separately enable it:

https://www.technipages.com/macos-enable-web-inspector-in-safari

SWISH just lists errors in the toplevel, and you can click them to get into the source:

![grafik](https://user-images.githubusercontent.com/5411487/42710473-761985c2-86e4-11e8-8bc0-0a890ae55d7a.png)

**Comment by ghost** [comment]
@UWN Also SICStus Prolog seems to not implement this part of 
the ISO module standard, I get the following result:

![grafik](https://user-images.githubusercontent.com/5411487/42716033-ee5b23d2-86f9-11e8-8fa0-8204676c2e91.png)

**Comment by UWN** [comment]
@jburse, see 6.4.4.2 of 13211-2
