### ISSUE TITLE
char_code/2: missing representation error

### ISSUE THREAD

**Issue by UWN** [jariazavalverde/tau-prolog#37]
```
?- M = 1114110,char_code(C,M), char_code(C,N), M = N.
false.                         % incorrect
```
When converting a code to characters and back one should always get the very same code.

```
?- M = 1114110,char_code(C,M), char_code(C,N).
M = 1114110, C = '￾', N = 65534.            % incorrect
```
It seems you are only supporting [Unicode 1.1](http://www.babelstone.co.uk/Unicode/HowMany.html). So for other integers that are not character codes a `representation_error(character_code)` should be issued.

Already perfect:

```
?- char_code(a, non_integer).
uncaught exception: error(type_error(integer, non_integer), '/'(char_code, 2))
```

**Comment by jariazavalverde** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/charCodeAt

> Note that `charCodeAt()` will always return a value that is less than 65536. This is because the higher code points are represented by a pair of (lower valued) "surrogate" pseudo-characters which are used to comprise the real character. Because of this, in order to examine or reproduce the full character for individual characters of value 65536 and above, for such characters, it is necessary to retrieve not only `charCodeAt(i)`, but also `charCodeAt(i+1)` (as if examining/reproducing a string with two letters), or to use `codePointAt(i)` instead. See example 2 and 3 below.

**Comment by jburse** [comment]
I was using surrogate pairs in my Prolog system to extend the codepoint range above 65535. But this is quite complicated, and renders some of the built-ins much slower. You can start thinking about it what it means for atom_length/2. The source code of all this is here:

atom_length(Str, Len) :-
    sys_atom_word_len(Str, Count),
    sys_atom_word_count(Str, 0, Count, Len).
https://github.com/jburse/jekejeke-devel/blob/master/jekrun/headless/jekpro/reference/structure/atom.p

https://github.com/jburse/jekejeke-devel/blob/master/jekrun/headless/jekpro/reference/structure/ForeignAtom.java

**Comment by UWN** [comment]
@jariazavalverde: For the standard, and all `_char` and `_code` built-ins, like `get_char/1`, there is only a PCS (Processor character set) where each character maps to a collating sequence integer (vulgo: character code). So any such encoding is only visible on the byte level with `get_byte/1`. It seems that all of this is quite costly to implement. So as a first start, simply produce a representation error whenever you have such problems.

**Comment by jburse** [comment]
Not really, get_byte/1 has to do with byte streams and is rather externally, and competely independent of text streams. Nothing to do how strings respectively atoms are interenally represented. Also if you go the route write some text read some bytes, you only see what the text encoding does, bot not how strings respectively atoms are internally represented.

Obviously from the JavaScript docu, the JavaScript strings use surrogate pair. Y
ou would see them when you use as text encoding UTF-16. 

https://en.wikipedia.org/wiki/UTF-16
**U+0000 to U+D7FF and U+E000 to U+FFFF**
Both UTF-16 and UCS-2 encode code points in this range as single 16-bit code units that are numerically equal to the corresponding code points. 

**U+10000 to U+10FFFF**
The top ten bits (a number in the range 0x0000..0x03FF) are added to 0xD800 to give the first 16-bit code unit or high surrogate, which will be in the range 0xD800..0xDBFF.
The low ten bits (also in the range 0x0000..0x03FF) are added to 0xDC00 to give the second 16-bit code unit or low surrogate, which will be in the range 0xDC00..0xDFFF.

But anything that considers bytes, when charAt() already returns a word, is 
anyway inefficient. From the JavaScript docu you see that charAt() already
returns a word. So all you have to do is sometimes combine two words
into a single code point.

**Comment by jburse** [comment]
I see, you are already having fun with Unicode:
https://twitter.com/tau_prolog/status/1056350064560521217
