### ISSUE TITLE
UMD support

### ISSUE THREAD

**Issue by LeonardoVal** [jariazavalverde/tau-prolog#4]
Would be much appreciated to be able to load and use the module outside the browser. Support for CommonJS (for NodeJS) and RequireJS may be easy to implement.

**Comment by josegarciaclm95** [comment]
Hello @LeonardoVal 

We've prepared Tau Prolog so it can be used in NodeJS just as requested.

You can find a little tutorial on how to use Tau Prolog in Nodejs [here ](http://tau-prolog.org/manual/compatibility-with-nodejs)(english) and [here ](http://tau-prolog.org/manual/es/compatibilidad-con-nodejs)(spanish).

Thanks for using Tau Prolog!
