### ISSUE TITLE
atom_codes/2 needs a quick fix to make it safe

### ISSUE THREAD

**Issue by jburse** [jariazavalverde/tau-prolog#40]
This is related to this isssue https://github.com/jariazavalverde/tau-prolog/issues/37, 
but I opening a new issue, since it has an additional complexity and is a different
predicate and might be overlooked. I currently get the following unexpected result:

![fofo](https://user-images.githubusercontent.com/5411487/43044928-8e8bc7f6-8daf-11e8-986d-34a53a99cb33.png)

**Comment by jburse** [comment]
This is the expected result. If your prolog system supports a
larger character range then the result can be as in SWI7:

![swi_fofo](https://user-images.githubusercontent.com/5411487/43044970-162c9bd6-8db0-11e8-86a7-b5e3e7b509a9.png)

**Comment by jburse** [comment]
On the other hand if your Prolog system doesn't support
a larger character range then the result be as in GNU:

![gnufofo](https://user-images.githubusercontent.com/5411487/43044989-4dff7876-8db0-11e8-9846-2f9b0aa43e6d.png)

**Comment by jburse** [comment]
You could fix it already, before enlarging the code range. It 
cost you nothing to add a representation error everywhere 
where char codes are used. Its legal for a prolog processor to

only support small range. You could go for an intermediate 
solution like GNU-Prolog, which would make your system more safer.
You could use this issue to track the intermediate solution.

Because introducing surrogate pairs respectively a larger code
range can take months and years. You also need to adapt the
Prolog scanner and parser. It must go through the whole Prolog

system to have a behaviour like SWI7 on the Mac. But on the other
a behaviour like GNU can be done very quickly.

**Comment by jariazavalverde** [comment]
Fixed #37 in 46e1a16507c2f2f32593259a9d09d0d643c499ff.
