### ISSUE TITLE
Feature request write family of predicates in the sandbox

### ISSUE THREAD

**Issue by jburse** [jariazavalverde/tau-prolog#41]
Would it be possible to allow write inside the sandbox? 
Currently these ISO core standard predicates are simply 
not recognized:

![grafik](https://user-images.githubusercontent.com/5411487/43187306-55cd2678-8ff1-11e8-9009-55272e581444.png)

But interestingly SWISH allows them;

![grafik](https://user-images.githubusercontent.com/5411487/43187357-7570a91e-8ff1-11e8-9269-165731236eeb.png)

**Comment by jariazavalverde** [comment]
I just added `read` and `write` families of predicates. Currently, the user output is the console of the browser and the user input is the prompt. Also it's possible to create (virtual) files with `open/[3-4]`. Now I'm adding an interface for Node.js and for the DOM (html objects).

**Comment by ghost** [comment]
Thanks for the update. Is there a documentation? Do you already
support the ISO core write option variable_names/2 ? Do you
support write/1 only or also write_term/2, that takes an option list?

**Comment by jariazavalverde** [comment]
We'll document it throughout these weeks. The predicates added are:
- current_input/1
- current_output/1
- set_input/1
- set_output/2
- open/[3-4]
- close/[1-2]
- get_char/[1-2]
- get_code/[1-2]
- put_char/[1-2]
- put_code/[1-2]
- nl/[0-1]
- read/[1-2]
- read_term/[2-3]
- write/[1-2]
- writeq/[1-2]
- write_canonical/[1-2]
- write_term/[2-3]

And soon the rest will be added (`get_byte`, `put_byte`, etc). `read_term` supports `variables`, `variable_names` and `singletons`.
