### ISSUE TITLE
vertical bar cannot be defined as operator

### ISSUE THREAD

**Issue by jburse** [jariazavalverde/tau-prolog#45]
It seems that inside the program sections one can define
operators. Here is an example of (++)/2 operator:

![grafik](https://user-images.githubusercontent.com/5411487/43848159-aa7b4582-9b32-11e8-899f-728aac166bb9.png)

**Comment by jburse** [comment]
But somehow the definition mechanism does not yet
work for the operator ('|')/2. Its also not predefined.

![grafik](https://user-images.githubusercontent.com/5411487/43848292-e16dedce-9b32-11e8-923f-db879b1c0131.png)

**Comment by jariazavalverde** [comment]
https://www.complang.tuwien.ac.at/ulrich/iso-prolog/dtc2

> A bar (6.4) shall be equivalent to the atom '|' when '|' is an operator.
> An operator '|' shall be only an infix operator with priority greater than or equal to 1001.

**Comment by jburse** [comment]
Yes, in the following statement:

:- op(1105,xfy,'|').

The priority 1105 is greater or equal to 1001.
So the op/3 directive is allowed according to DTC2.

**Comment by jariazavalverde** [comment]
Yes, that's just a note I leave for myself, sorry. The problem was fixed yesterday.

![bar](https://user-images.githubusercontent.com/5055295/47722307-6aadbc80-dc52-11e8-8120-87bb11c7acda.png)
