### ISSUE TITLE
Clarification of documentation

### ISSUE THREAD

**Issue by rla** [jariazavalverde/tau-prolog#46]
Documentation "Prototypes and Prolog objects" lists two JavaScript prototypes:

 * Var (variables)
 * Term (compounds and atoms)

The code seems to also have Num, which seems to be for numbers but is not documented.

I am currently designing API for JS and SWI-Prolog (wasm build) interoperability and was looking how other JS-Prolog libraries do it.

**Comment by josegarciaclm95** [comment]
Hello @rla . The English version of the docs is not fully translated yet. The Spanish docs are more matured, but they are not up to date either. We'll update them both as soon as we can!

**Comment by josegarciaclm95** [comment]
Hello again @rla. The "Prototypes and Prolog objects" page has been updated.
