### ISSUE TITLE
Derivation tree: What happens to subgoals, like in findall/3?

### ISSUE THREAD

**Issue by jburse** [jariazavalverde/tau-prolog#55]
Just noticed new derivation tree feature. What happens to subgoals, like the 
goal argument in findall/3. It disappears, but may naive expectation is to see it:

![grafik](https://user-images.githubusercontent.com/5411487/47617598-10cdbb00-dac9-11e8-8ce0-d29ecd3c003d.png)

**Comment by ghost** [comment]
From other testing I see that by derivation tree you understand a 
complete derivation tree or up to max answer. So (X=1;X=2) has a 

complete derivation tree but it gets not show by a findall/3 invocation. 
This might be a design decision of the derivation tree visualizer, or 

maybe an option somewhere?

![grafik](https://user-images.githubusercontent.com/5411487/47617656-a6694a80-dac9-11e8-8443-507bbe764dfb.png)

**Comment by jariazavalverde** [comment]
That's because some subgoals are calculated in separate threads of the session, and the pointers to those nodes are not collected. But the tree shows all the answers:

![bagof](https://user-images.githubusercontent.com/5055295/47617710-41622480-daca-11e8-95bd-1ed4327e8dc5.png)

**Comment by ghost** [comment]
findall/3 has only one answer. The bagof/3 did run p(X,Y), so I don't see 
the p(X,Y) derivation when I run bagof/3? No option or plans to see this?

**Comment by jariazavalverde** [comment]
Not yet. I have to review those predicates to try to get the lost nodes.

**Comment by ghost** [comment]
Maybe findall/3 and bagof/3 are not high priority. But showing for example more
for (\\+)/1 could be interesting for teaching and research in negation as failure. 
What I figured out that once/1 works. You also show failed sub derivations by the 
color red, and the cut is correctly respected (Cool!):

?- X = b, once((X = a; X = b; X = c)).
![grafik](https://user-images.githubusercontent.com/5411487/47618232-f8619e80-dad0-11e8-8f28-e4c8d7815d4c.png)

But then for example the (\\+)/1, a fossile of meta predicate possibly subsumed
by more logical approaches, does not yet show any sub-derivation. I guess it
has a similar subderivation like the once/1 example, except for a different 
overall outcome:

![grafik](https://user-images.githubusercontent.com/5411487/47618250-33fc6880-dad1-11e8-8a69-a8d2dff11177.png)

**Comment by jariazavalverde** [comment]
Maybe this way?

`?- X = b,  \+ ((X = a; X = b; X = c)).`
![negation](https://user-images.githubusercontent.com/5055295/47623602-cd4c6e80-db13-11e8-985f-5a06b9ef895b.png)

`?- X = b, \+ ((X = a; X = c; X = d)).`
![negation-success](https://user-images.githubusercontent.com/5055295/47623604-d2112280-db13-11e8-94c3-46626a4949ba.png)

**Comment by jariazavalverde** [comment]
Or better implemented with cut & fail?
```
not(X) :- call(X), !, false.
not(X).
```

`?- X = b, not((X = a; X = b; X = c)).`

![negation2](https://user-images.githubusercontent.com/5055295/47623941-00dcc800-db17-11e8-9864-0a4c482320d9.png)

`?- X = b, not((X = a; X = c; X = d)).`
![negation2-success](https://user-images.githubusercontent.com/5055295/47623943-0803d600-db17-11e8-882b-642432583f73.png)

**Comment by jariazavalverde** [comment]
I just fixed sub-derivations for the following predicates:

- \\+/1
- findall/3
- bagof/3
- setof/3
- catch
- ->;

If you find more predicates, you can reopen this issue. Thanks!


`?- findall((X,Y), append(X,Y,[1,2,3]), L).`

![findall](https://user-images.githubusercontent.com/5055295/47647002-074e5c80-db76-11e8-82e4-a5b9e1a7974a.png)
