### ISSUE TITLE
Filesystem library

### ISSUE THREAD

**Issue by arcanis** [jariazavalverde/tau-prolog#59]
I've seen that swi-pl seems to have an interesting library of [filesystem-related predicates](http://www.swi-prolog.org/pldoc/man?section=files). Is it something that would be possible in `tau-prolog`? It obviously wouldn't make sense from within a browser, but it could be valuable for Node applications.

**Comment by jariazavalverde** [comment]
> Our idea is to create a virtual file system which allows users to connect it with a file system of their choice. By default, we will offer one file system for JS in the browser and other one for Node.js.
> https://twitter.com/tau_prolog/status/1002509523775643648

Unfortunately, I don't have much time currently. Maybe in a few months...

**Comment by jariazavalverde** [comment]
Added in 19c49f6d0e352eed9b3fc973a788d74f458e9476.

**Comment by pmoura** [comment]
The 19c49f6 commit is not about the file system library... wrong issue?
