### ISSUE TITLE
Feature request term and goal expansion

### ISSUE THREAD

**Issue by jburse** [jariazavalverde/tau-prolog#60]
I tried term and goal expansion. But it seems not to be available:

![image](https://user-images.githubusercontent.com/5411487/48666376-8e7d5900-eac0-11e8-8fc0-f140f3d8329a.png)

The test case is from here:
https://github.com/hsk/simpletapl/blob/master/prolog_basis/README.md#goal_expansion

**Comment by jariazavalverde** [comment]
Added in ea31ee5b309a12ef09ef8682e7a7ca9de22e1e93.
Thanks for your request.

![expansion](https://user-images.githubusercontent.com/5055295/67458923-a4cc5700-f637-11e9-8eac-377afe527e55.png)
