### ISSUE TITLE
existence error for foldl/4

### ISSUE THREAD

**Issue by mad-mike** [jariazavalverde/tau-prolog#61]
Hi,

*I'm new to Prolog as well as Tau-Prolog, so I ask for forgiveness if what follows is incorrect.*

I've been trying to use the [foldl/4](http://tau-prolog.org/documentation/prolog/lists/foldl/4) predicate to unnest a list of lists, but have always run into `error(existence_error(procedure, '/'(foldl, 4)), '/'(top_level, 0))`.

Simple example:

```
:-use_module(library(lists)).
?- foldl(append, [[a],[b]], [], X).
```
expected result: `X = [a,b]`

When I copy the supposed definition of `foldl` from the documentation, it works as expected:
```
:-use_module(library(lists)).

my_foldl(_, [], I, I).
my_foldl(P, [H|T], I, R) :- ('=..'(P, L), (append(L, [I, H, X], L2), ('=..'(P2, L2), (call(P2), my_foldl(P, T, X, R))))).

?- my_foldl(append, [[a],[b]], [], X).
X = [a, b].
```

Reviewing the implementation of `foldl` I'm beginning to think that there might be a typo in https://github.com/jariazavalverde/tau-prolog/blob/a2082f0d59214b9d14ee866f04feb9c3e232bb7d/modules/lists.js#L342 . All predicates are listed with exactly the key that they were defined with above, but instead of the expected `foldl/4`, this line has only `fold/4`.

Could an expert please check?

**Comment by mad-mike** [comment]
@jariazavalverde that was one astonishingly quick reaction.
I'm using the npm module, so please notify me when you plan to publish a new version with this fix.

**Comment by jariazavalverde** [comment]
> All predicates are listed with exactly the key that they were defined with above, but instead of the expected foldl/4, this line has only fold/4.

That's the problem, I just fixed it. Thanks for your report.

We'll notify you when we update the npm package.
