### ISSUE TITLE
Feature request write_term ignore_ops(false)

### ISSUE THREAD

**Issue by jburse** [jariazavalverde/tau-prolog#66]
Hi,

Started playing around with your transformations panels for the first time.
Have a feature request. Would it be possible to write the clauses with
ignore_ops(false) (see ISO prolog):

**ignore_ops(false)**
the same as [operators(true),dotlists(false),transform(true)]. ISO-Prolog compatibility. 
http://eclipseclp.org/doc/bips/kernel/ioterm/write_term-3.html

Currently the transformation panel shows them with ignore_ops(true) I guess:

![ignore_ops](https://user-images.githubusercontent.com/5411487/50795128-8924d980-12cd-11e9-952a-49ac1ae39f93.gif)

**Comment by jburse** [comment]
I guess the expected result would be:

```
data((X is 1+2,  _ is 10*X)). 
data((X is 3*4, _ is 9+X)). 
  
eval :- data(X), call(X).
```

**Comment by jburse** [comment]
But otherwise it works fine. Question: What is the aim of the transformation
panel? Some step by step execution mechanism or something else? Like
testing inline strategies for Prolog compilation?

**Comment by jariazavalverde** [comment]
Done, although I still have to improve some things in the operator form.

![write_options](https://user-images.githubusercontent.com/5055295/54236824-d6633880-4514-11e9-9893-0ecb4003635b.png)

> Question: What is the aim of the transformation panel?

Purely academic, by the moment.

**Comment by jburse** [comment]
Thanks for the update. When I have time, 
I will think about some nasty test cases.
