### ISSUE TITLE
call/2..8 and many other built-ins missing

### ISSUE THREAD

**Issue by UWN** [jariazavalverde/tau-prolog#7]
[Here](http://www.complang.tuwien.ac.at/ulrich/iso-prolog/prologue#status_quo) is a list of various features the Prolog standards are defining. I am rather surprised that you define `maplist/3`, but do not define `call/2`. (It seems you took a rather outdated list as basis. In the meantime we had 3 corrigenda. See [this](http://www.complang.tuwien.ac.at/ulrich/iso-prolog/) for more.

**Comment by jariazavalverde** [comment]
The following predicates have been added from [DTC2](http://www.complang.tuwien.ac.at/ulrich/iso-prolog/dtc2):
- call/2..8
- false/0
- subsumes_term/2
- retractall/1
- term_variables/2
- compare/3
- acyclic_term/1
- callable/1
- ground/1
- keysort/2
- between/3
- succ/2
- select/3
- maplist/2..8

And the arithmetic functors:
- max/2
- min/2
- xor/2
- asin/2
- acos/2
- atan2/2
- (^)/2

Thank you very much for the links, @UWN.
