### ISSUE TITLE
One of the links on the documentation page is broken

### ISSUE THREAD

**Issue by jarble** [jariazavalverde/tau-prolog#74]
[This link](http://tau-prolog.org/manual/manipulating-the-dom-with-prolog) on Tau Prolog's [documentation page](http://tau-prolog.org/documentation) currently seems to be broken. Can this link be updated so that it links to the correct page?

**Comment by josegarciaclm95** [comment]
Hi @jarble. Yes, some sections of the manual are still in development. We'll complete the [Manipulating the DOM with Prolog](http://tau-prolog.org/manual/manipulating-the-dom-with-prolog) section throughout this week. In the meanwhile, the [DOM module docs](http://tau-prolog.org/documentation#dom) and the [little doge](http://tau-prolog.org/examples/my-little-doge) example may be of assistance.

**Comment by josegarciaclm95** [comment]
Hi again @jarble. I've just uploaded the manual, both to github and to the webpage. The link [Manipulating the DOM with Prolog](http://tau-prolog.org/manual/manipulating-the-dom-with-prolog) works now.
