### ISSUE TITLE
negation of failure should not be cut transparent

### ISSUE THREAD

**Issue by jburse** [jariazavalverde/tau-prolog#76]
Hi,

I get two times false:

![image](https://user-images.githubusercontent.com/5411487/54088369-bccbc080-435d-11e9-8ca4-e50f1fc32edc.png)

But according to the ISO core standard, the first query should 
give false, and the second query should give true.

**Comment by jburse** [comment]
Basically (\+)/1 should open a context like call/1, and then flip the result 
from true to false, and from false to true. You can compare with GNU Prolog:

![image](https://user-images.githubusercontent.com/5411487/54088394-074d3d00-435e-11e9-9535-85f93d1c76c1.png)

**Comment by jariazavalverde** [comment]
Fixed, thanks for the notice!

**Comment by jburse** [comment]
Do you think this is also fixed:

**Comment by jburse** [comment]
The expected result is also:

![image](https://user-images.githubusercontent.com/5411487/54092099-67f16f80-4388-11e9-9c5b-78d367e05d09.png)

**Comment by jariazavalverde** [comment]
Fixed. Cuts inside goals of `call/1` were not local to the goal. Thanks.

![not](https://user-images.githubusercontent.com/5055295/54092736-f3baca00-438f-11e9-85e9-8f6fca52ca94.png)

**Comment by jburse** [comment]
Nice!
