### ISSUE TITLE
Slow length/2

### ISSUE THREAD

**Issue by UWN** [jariazavalverde/tau-prolog#8]
(This is a classical performance bug. So welcome to the club!)

<pre>?- N=1000,\+ ( length(L,M), N = M ).
limit exceeded ;
</pre>
This should not take that long. I suspect you have quadratic overhead here. `length(L, M)` should enumerate all lists starting with `[]`, `[_]` etc. each further answer should require only constant runtime. But I suspect you are somehow spending linear time **per answer** - hence quadratic overhead.

**Comment by UWN** [comment]
It seems that the problem is not your definition itself, but rather your system as such. Using:

```
mylen([], N,N).
mylen([_|Es], N0,N) :-
   N1 is N0+1,
   mylen(Es, N1,N).
```

I only get a little bit further:

```
?- N=135,\+ ( mylen(L,0,M), N = M ).
false.
```

For 135 inferences in mylength  + 135 times for (=)/2 you should not need so much time.

**Comment by jariazavalverde** [comment]
Thank you for your tests, @UWN. I'm working on the improvement of the resolution of our system. Now, with 10000 steps (default in the sandbox), the maximum is between `N = 2000` and `N=2500`.

![limit length/2](https://user-images.githubusercontent.com/5055295/41154800-9c3497e0-6b1b-11e8-9184-1656e91930d7.png)

**Comment by UWN** [comment]
With limit 10000, `N = 2498` still works!
And with limit 5000, `N=1248`. So this looks pretty linear to me.

You have 4 steps per solution of length. With those you have to:

- fetch the continuation
- unify, and then
- backtrack into `length/2`, and there
- perform an arithmetical operation (+ 1),
- then take the recursive step
