### ISSUE TITLE
sandbox: save dialog cannot be cancelled

### ISSUE THREAD

**Issue by UWN** [jariazavalverde/tau-prolog#80]
1. Press Save in the Menu of the sandbox.
2. A nice dialog box is show asking for Title and Description
3. Now, I do not want to save what I did, but want to continue writing my program
4. Neither [Escape] work, nor I see any Cancel box.
5. So I am now forced to give up what I did or do an unnecessary save

**Comment by UWN** [comment]
Actually, it can be cancelled by clicking again on the menu item save. But this is really very un-intuitive.

**Comment by jariazavalverde** [comment]
Done! Now the dialogs are cancelled by clicking out of them. Thanks for your suggestion.
