### ISSUE TITLE
require('tau-prolog/modules/js') TypeError 'pl' is undefined

### ISSUE THREAD

**Issue by PaulBrownMagic** [jariazavalverde/tau-prolog#83]
Using version 0.2.65 (install via npm), I'm using it within a Vue application with Webpack.
Including the lists module as per the docs for use with node, no errors raised:
```
const pl = require(tau-prolog)
require('tau-prolog/modules/lists')(pl)
```
Doing the same with js module:
```
const pl = require(tau-prolog)
require('tau-prolog/modules/js')(pl)
```
The part `require('tau-prolog/modules/js')` is sufficient to cause `TypeError: pl is undefined`, pointing to line 108 and 203.

**Comment by MiguelRiazaValverde** [comment]
Fixed! Thanks for the report. We'll update the package in npm in a few hours.

**Comment by josemariagarcia95** [comment]
The npm package has been just uploaded, new version is `0.2.66`.
