### ISSUE TITLE
Does Tau Prolog provide last call optimization?

### ISSUE THREAD

**Issue by jburse** [jariazavalverde/tau-prolog#84]
Hi, 

How could I run this query in Tau Prolog?

```
inside(I,_,I).
inside(I,J,K) :-
       I<J,
       L is I+1,
       inside(L,J,K). 

?- inside(1,1000000,X), fail.
```

It shows me "limit exceeded ;" even if I change the Query limit to
something like 10000000. Or is Query limit in the sandbox something
else, yet another limit?

Bye

**Comment by jariazavalverde** [comment]
The limit is the maximum number of resolution steps that Tau Prolog performs in a search. If you get "limit exceeded" you can press enter again to continue the search where it stopped. Right now Tau Prolog doesn't provide last call optimization.

**Comment by jburse** [comment]
Aha, Ok.
