### ISSUE TITLE
Feature: get_by_name/2

### ISSUE THREAD

**Issue by PaulBrownMagic** [jariazavalverde/tau-prolog#85]
In the DOM module we have `get_by_id/2`, `get_by_class/2`, and `get_by_tag/2`. However, when working with forms, particularly checkboxes and radio buttons, it would also be useful to have `get_by_name/2`, which would proxy `document.getElementByName`.

I'm guessing the existing implementations could be adapted to just change the JavaScript function called? 

My use case is to find which one of a group of radio buttons has been checked.

**Comment by jariazavalverde** [comment]
Hi @PaulBrownMagic, thanks you for your suggestion.

Next week I will add the predicate `get_by_name/2` and make other changes to the DOM package. Meanwhile, you can use the following predicate to search for elements by name:

```prolog
get_by_name(Name, HTML) :-
    get_by_tag(*, HTML),
    attr(HTML, name, X),
    X = Name.
```

**Comment by jariazavalverde** [comment]
The following predicates have been added:
- `get_by_name/2`
- `get_by_tag/3`
- `get_by_class/3`
- `document/1`, `head/1`, `body/1`
- `attr/3` => `set_attr/3`, `get_attr/3`
-  `style/3` => `set_style/3`, `get_style/3`
- `html/2` => `set_html/2`, `get_html/2`
