### ISSUE TITLE
bug in atom_codes/2 ?

### ISSUE THREAD

**Issue by jburse** [jariazavalverde/tau-prolog#86]
I cannot make head nor tail what is going on here:

![Unbenannt](https://user-images.githubusercontent.com/5411487/63060516-d23bac80-bef2-11e9-962c-a664ace91268.PNG)

My expectation was:

```
?- X = 'Welcome in \x1F1EC\', atom_codes(X,L).
X = 'Welcome in 🇬',
L = [87, 101, 108, 99, 111, 109, 101, 32, 105, 110, 32, 127468]
```

**Comment by jariazavalverde** [comment]
Fixed.

![atom_codes](https://user-images.githubusercontent.com/5055295/63362919-e9efb680-c372-11e9-976e-a1c357a3045a.png)
