### ISSUE TITLE
strange slowdown when typing query larger than input field

### ISSUE THREAD

**Issue by jburse** [jariazavalverde/tau-prolog#88]
I get this errror:

![Unbenannt](https://user-images.githubusercontent.com/5411487/63363654-4dc6af00-c374-11e9-85c6-9c47415cb38d.PNG)

![image](https://user-images.githubusercontent.com/5411487/63363604-3091e080-c374-11e9-8c50-45ce43150800.png)

Also chrome kind of halts when the right margin of the query field is reached.

**Comment by ghost** [comment]
Not sure whether related to:
https://github.com/jariazavalverde/tau-prolog/issues/86

I wanted to regression test the above issue.

**Comment by MiguelRiazaValverde** [comment]
Fixed (f36a74f88a464a4d7dd6dcdcc4c9b4ab6ee98a29). Thanks for your report.

**Comment by jburse** [comment]
Weekends are for TauProlog! What was the problem?
