### ISSUE TITLE
setof/3 not removing duplicates?

### ISSUE THREAD

**Issue by marcusedwards-cp** [jariazavalverde/tau-prolog#91]
sort/2 does return the sorted list and remove duplicates:

?- sort([a,a,b,c,b,a], L).
L = [a,b,c]

However, setof/3 (which says it uses sort/2 to order the results and remove duplicates) does not.

foo(a).
foo(a).
foo(b).
foo(c).
foo(b).
foo(a).

?- findall(X, foo(X), L).
L = [a,a,b,c,b,a]

?- setof(X, foo(X), L).
L = [a,a,a,b,b,c]

**Comment by jariazavalverde** [comment]
Hi @marcusedwards-cp. Fixed! Thanks for your report.
